import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import "./globals.css";
import StyledJsxRegistry from "./registry";
import StyledComponentsRegistry from "../lib/registry";
import Navbar from "../components/Navbar";

const roboto = Roboto_Flex({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={roboto.className}>
      <body>
        <StyledComponentsRegistry>
          <Navbar />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
